name: build and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: build
        run: |
          npm install
          npm run docs:build

      - name: config
        run: |
          git config --local user.email "dinglei0916@outlook.com"
          git config --local user.name "dinglei"

      - name: token
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: publish
        run: |
          cd release/.vuepress/dist
          git init
          git add -A
          git commit -m "deploy"
          git push -f git@github.com:IgreatD-Siiri/siiri-release.git master:gh-pages
